### PR TITLE
bugfix: index out of range

### PR DESCRIPTION
**Pull request by soulmachine**
The command `testrpc -a 3` will create three accounts at startup, so the maximal index of accounts is 2 instead of 3

### CODE REVIEW

**Comment by sot528** [comment]
@soulmachine 
You are right.
Thank you 😉

**Comment by soulmachine** [comment]
Hi Sota, since I can not find your email so I just left this question here. If I upgrade zeppelin to 1.3.0 in the file `ethpm.json`, nothing else changed, when I deploy it to the private network with `truffle migrate`, I always get en error as following:

```
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xb33e5428bbec53930e90145cfb45130682c519dc8f7444be5826c012d86fb711
  Migrations: 0x8489f41bfaa00337bd55216277767e4bbcbd0a9b
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying AlisFund...
  ... 0x9f6a7360836d84a4bd6a49a5ebd4365a874e79b7ec48dfe374fbaf748a6c4575
  AlisFund: 0xe0d89b66cd3ff4444402b82189032176db92c93a
  Deploying AlisCrowdsale...
  ... 0xb185c437d92e293e94043d34e241b1c3e310f56eda37ea17a10039d9a63f78fa
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: invalid opcode
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:37312:16)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:220420:36
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:72910:11
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:204149:9
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:205574:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:73069:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:73359:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:73514:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:73474:24)
    at emitNone (events.js:110:20)
```

Do you happen to know why ?

**Comment by soulmachine** [comment]
Hi Sota, since I can not find your email so I just left this question here. If I upgrade zeppelin to 1.3.0 in the file `ethpm.json`, nothing else changed, when I deploy it to the private network with `truffle migrate`, I always get en error as following:

```
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xb33e5428bbec53930e90145cfb45130682c519dc8f7444be5826c012d86fb711
  Migrations: 0x8489f41bfaa00337bd55216277767e4bbcbd0a9b
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying AlisFund...
  ... 0x9f6a7360836d84a4bd6a49a5ebd4365a874e79b7ec48dfe374fbaf748a6c4575
  AlisFund: 0xe0d89b66cd3ff4444402b82189032176db92c93a
  Deploying AlisCrowdsale...
  ... 0xb185c437d92e293e94043d34e241b1c3e310f56eda37ea17a10039d9a63f78fa
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: invalid opcode
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:37312:16)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:220420:36
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:72910:11
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:204149:9
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:205574:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:73069:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:73359:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:73514:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:73474:24)
    at emitNone (events.js:110:20)
```

**Comment by takahiro096041** [comment]
It may be the specification change of the zeppelin.

・Zeppelin 1.2 →1.3
In version 1.2, crowdsale is made up with the parameter of start-block,end-block and icoStartTime.
But in version 1.3, crowdsale is made up with the parameter of icoStartTime and icoEndTime.
So, I think that you have to change the implementation of AlisCrowdsale.

**Comment by sot528** [comment]
@soulmachine 
Yeah, @takahiro096041 is right! Thank you :D

The issue about this problem:
https://github.com/OpenZeppelin/zeppelin-solidity/issues/350

Also PR:
https://github.com/OpenZeppelin/zeppelin-solidity/pull/353/files

This is big changes. 
Blocktime should NOT used to calculating time anymore.
Actually, it isn't works well because of **difficulty bomb** .


If you want to use zeppelin-solidity v1.3.0, you have to change our code a lot.
Or, if you don't want write new tests so much, then you can add one line of ending condition to: https://github.com/AlisProject/contracts/blob/master/contracts/AlisCrowdsale.sol#L69

ex: 
```javascript
function hasEnded() public constant returns (bool) {
  uint256 threshold = tokenCap.div(100).mul(99);
  bool thresholdReached = token.totalSupply() >= threshold;  

  // ADD THIS LINE
  bool endTimestampReached = now > 1507766400 // 12 Oct 2017(UTC)

  // ADD THE CONDITION ABOVE HERE
  return super.hasEnded() || thresholdReached || endTimestampReached;
}
```

Anyways, I'm highly recommend to you what using timestamp instead blocktime.
I wish you good luck 😉

**Comment by soulmachine** [comment]
@takahiro096041 @sot528  Thank you guys, I changed my code as you suggested above, it works now!

**Pull request merged**
